### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Elyriand21** [Lillious/Lethal-Company-Developer-Console#15]
Whenever the mission is completed *(the ship is launched back into orbit)*, the dev console will no longer be usable. The PlayerController is not disabled when the console is pulled up so no commands can be typed in.

**Comment by Lillious** [comment]
Both @Elyriand21 and I are unable to reproduce but will keep this open in-case there is a random edge case that causes this to occur. Will close after 30 days.

**Comment by Lillious** [comment]
This was discovered again but is now fixed.
