### ISSUE TITLE
Terminal Set Group Credits

### ISSUE THREAD

**Issue by Elyriand21** [Lillious/Lethal-Company-Developer-Console#19]
Whenever `set group_credits <value>` is used, something has to be bought before the credits are updated on the screen

**Comment by Lillious** [comment]
Proposed change
```cs
SyncGroupCreditsServerRpc(int newGroupCredits, int numItemsInShip)
```
Still will need to calculate the `numItemsInShip` value.
With the below attribute, LC does not need explicit ownership when calling the above ServerRpc method.
```cs
[ServerRpc(RequireOwnership = false)]
```

**Comment by Lillious** [comment]
`numItemsInShip` can be set from the `numberOfItemsInDropship` client value under the `Terminal` component

**Comment by Lillious** [comment]
Fixed in dev branch of mod library
