### ISSUE TITLE
version 1.14-a .dll file casues mod not to load

### ISSUE THREAD

**Issue by LoneWolfGmer** [Lillious/Lethal-Company-Developer-Console#39]
i don't get what this much means any more than most people but this is what it gives me 
![image](https://github.com/Lillious/Lethal-Company-Developer-Console/assets/37723026/5ed3bc56-1a8f-415f-b615-92e03366f995)

**Comment by Lillious** [comment]
This issue is with Lethal Library but the issue appears to be caused by a bug in visual studio building an incomplete dll file.

**Comment by Lillious** [comment]
Latest versions removed until a fix is found. I am actively working on this.

**Comment by Lillious** [comment]
This has been fixed. 👍
